In [2]:
import numpy as np
import tensorflow as tf

def pixel_shuffle(input_tensor, scale):
    # Get the shape of the input tensor
    batch_size, height, width, channels = input_tensor.shape

    # Calculate new dimensions
    new_height = height * scale
    new_width = width * scale
    new_channels = channels // (scale * scale)

    # Reshape the input tensor
    reshaped_tensor = tf.reshape(input_tensor, (batch_size, height, width, scale, scale, new_channels))

    # Transpose the tensor dimensions
    transposed_tensor = tf.transpose(reshaped_tensor, (0, 1, 3, 2, 4, 5))

    # Reshape to the final output shape
    output_tensor = tf.reshape(transposed_tensor, (batch_size, new_height, new_width, new_channels))

    return output_tensor

# Ví dụ đầu vào
batch_size = 1
height = 2
width = 2
channels = 4
scale = 2

input_tensor = np.array([[[[1, 2, 3, 4],
                           [5, 6, 7, 8]],
                          [[9, 10, 11, 12],
                           [13, 14, 15, 16]]]], dtype=np.float32)
print(input_tensor.shape)

print("Input Tensor:")
print(input_tensor)

# Chuyển đổi sang TensorFlow tensor
input_tensor_tf = tf.constant(input_tensor)

# Áp dụng Pixel Shuffle
output_tensor_tf = pixel_shuffle(input_tensor_tf, scale)
print(output_tensor_tf.shape)
print("\nOutput Tensor:")
print(output_tensor_tf.numpy())


(1, 2, 2, 4)
Input Tensor:
[[[[ 1.  2.  3.  4.]
   [ 5.  6.  7.  8.]]

  [[ 9. 10. 11. 12.]
   [13. 14. 15. 16.]]]]
(1, 4, 4, 1)

Output Tensor:
[[[[ 1.]
   [ 2.]
   [ 5.]
   [ 6.]]

  [[ 3.]
   [ 4.]
   [ 7.]
   [ 8.]]

  [[ 9.]
   [10.]
   [13.]
   [14.]]

  [[11.]
   [12.]
   [15.]
   [16.]]]]
